[build-system]
requires = ["setuptools", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3*"
skip = "*-win32 *-musllinux_i686 *-manylinux_i686"
test-skip = "*_arm64 *_universal2:arm64"
test-command = "python -c \"from namespace import project\ndummy = project.Dummy()\ndummy.setVal(42)\nprint(dummy.getVal())\ndummy = project.Dummy(42)\n\""
environment = { DEPLOY = "ON" }
build-verbosity = 3

[tool.cibuildwheel.linux]

[tool.cibuildwheel.macos]
archs = "x86_64"
environment = { MACOSX_DEPLOYMENT_TARGET = "10.15", DEPLOY = "ON" }

[tool.cibuildwheel.windows]
